version: "3"
services:
  5etools-docker:
    container_name: 5etools-docker
    image: jafner/5etools-docker
    volumes:
      - 5etools-data:/usr/local/apache2/htdocs
    ports:
      - 8080:80/tcp
    environment:
      - IMG=FALSE # Set to TRUE to pull images from https://github.com/5etools-mirror-2/5etools-img (as a Git submodule)
      - PUID=1000
      - PGID=1000
      - DL_LINK=https://github.com/5etools-mirror-3/5etools-src.git
      #- OFFLINE_MODE=TRUE # Optional. Expects "TRUE" or "FALSE". Disables checking for new updates.

volumes:
  5etools-data:
